FROM centos:7
LABEL maintainer="Vitaly Uvarov <v.uvarov@dodopizza.com>"

WORKDIR /nginx_modules

ARG NGINX_VERSION="nginx-1.15.2-1"
ARG OPENSSL_VERSION="openssl-1.0.2m" 

RUN     yum install -y \
            epel-release wget git \
            redhat-lsb-core \
            openssl openssl-devel geoip-devel \
            rpmdevtools gcc gcc-c++ make automake autoconf libtool \ 
        && yum clean all -y


## The OpenSSL library – required by NGINX SSL modules to support the HTTPS protocol
RUN     cd "${WORKDIR}" \
        && wget "https://www.openssl.org/source/${OPENSSL_VERSION}.tar.gz" \
        && tar -zxf "${OPENSSL_VERSION}.tar.gz" \
        && cd "${OPENSSL_VERSION}" \
        && ./config \
        && make test \
        && make install \
        \
        # If the old version is still displayed or installed before,
        # Making a copy of openssl bin file :
        && ( mv /usr/bin/openssl{,.old} || true ) \
        && ln -s /usr/local/ssl/bin/openssl /usr/bin/openssl \
        && openssl version

##
## NGINX
##

# Cloning nginx-module-vts
RUN     cd "${WORKDIR}" \
        && git clone https://github.com/vozlt/nginx-module-vts.git 

# Cloning ngx_dynamic_upstream module
RUN     cd "${WORKDIR}" \
        && git clone https://github.com/cubicdaiya/ngx_dynamic_upstream.git

# Fetching nginx prebuild
RUN     cd "${WORKDIR}" \
        && rpm -Uvh "http://nginx.org/packages/mainline/centos/7/SRPMS/${NGINX_VERSION}.el7_4.ngx.src.rpm"

RUN     echo "--with-debug --with-http_geoip_module " > /args \
        && echo "--add-module='${WORKDIR}/nginx-module-vts' " >> /args \
        && echo "--add-module='${WORKDIR}/ngx_dynamic_upstream' " >> /args

RUN     awk '/--with-debug/{system("cat /args");next}1' ~/rpmbuild/SPECS/nginx.spec

RUN     rpmbuild -bb ~/rpmbuild/SPECS/nginx.spec